### ISSUE TITLE
Why ignore package-lock.json?

### ISSUE THREAD

**Issue by l0b0** [stac-extensions/template#8]
Why is this file excluded from the repo? It's pretty common nowadays to commit the lock file.

**Comment by m-mohr** [comment]
The decision was made as we are not sharing (JS) code here thus is not very crucial to stay on exactly the same versions of npm always. Actually, you want the checks to always run on the latest versions usually, otherwise, we would need to update the files more regularly, which brings additional costs in maintenance. Also, package-lock.json files often lead to merge conflicts or issues without the users knowing how to handle them as we are not having JS-centric developers in the extension repos. So overall it feels like the better choice to not commit it here. I don't actually see a single good reason to commit them... do you have one in mind?

**Comment by l0b0** [comment]
I probably couldn't put it better than [this discussion](https://stackoverflow.com/q/44206782/96588). One choice bit is that not every project follows semver perfectly, so basically any upgrade could be breaking. Debugging why things are working on one machine but not another is a huge pain.

Re. upgrades, Dependabot can easily be added to automatically upgrade when new versions are released. That way package.json dependencies can usually be left as "*", since you only need to specify a version if you don't want to upgrade to the latest version yet.

**Comment by m-mohr** [comment]
If it's important for your extension or environment, feel free to change the .gitignore and commit the package-lock.json file. For most other extensions we won't make the effort for the reasons mentioned above.
